---
oc_mirror_download_url: "https://mirror.openshift.com/pub/cgw/mirror-registry/latest/mirror-registry-amd64.tar.gz"
oc_mirror_tmp_file: "/tmp/oc-mirror.tar.gz"
oc_mirror_extract_path: "/tmp/oc-mirror"
oc_mirror_install_path: "/usr/local/bin/oc-mirror"
