  
- name: Download oc-mirror archive
  get_url:
    url: "{{ oc_mirror_download_url }}"
    dest: "{{ oc_mirror_tmp_file }}"
    mode: '0644'

- name: Create temporary directory for oc-mirror extraction
  file:
    path: "{{ oc_mirror_extract_path }}"
    state: directory

- name: Extract oc-mirror
  unarchive:
    src: "{{ oc_mirror_tmp_file }}"
    dest: "{{ oc_mirror_extract_path }}"
    remote_src: yes

- name: Copy oc-mirror binary to install path
  copy:
    src: "{{ oc_mirror_extract_path }}/oc-mirror"
    dest: "{{ oc_mirror_install_path }}"
    mode: '0755'
